In [1]:
import pandas as pd
from sklearn import *
from sklearn.preprocessing import *

In [3]:
df = pd.read_csv("E:/Tugasku/data mining/21083010040_Calvien Danny_DMC/employee.csv")

df.head()

name   age   income gender  department grade  performance_score
0    Allen Smith  45.0      NaN    NaN  Operations    G3                723
1        S Kumar   NaN  16000.0      F     Finance    G0                520
2    Jack Morgan  32.0  35000.0      M     Finance    G2                674
3      Ying Chin  45.0  65000.0      F       Sales    G3                556
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2                711

In [4]:
print(df.columns)

Index(['name', 'age', 'income', 'gender', 'department', 'grade',
       'performance_score'],
      dtype='object')


In [5]:
df.describe()

age        income  performance_score
count   7.000000      7.000000           9.000000
mean   40.428571  52857.142857         610.666667
std    12.204605  26028.372797         235.671912
min    23.000000  16000.000000          53.000000
25%    31.000000  38500.000000         556.000000
50%    45.000000  52000.000000         674.000000
75%    49.500000  63500.000000         711.000000
max    54.000000  98000.000000         901.000000

In [6]:
df[2:5]

name   age   income gender  department grade  performance_score
2    Jack Morgan  32.0  35000.0      M     Finance    G2                674
3      Ying Chin  45.0  65000.0      F       Sales    G3                556
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2                711

In [7]:
df["name"]

0      Allen Smith
1          S Kumar
2      Jack Morgan
3        Ying Chin
4    Dheeraj Patel
5    Satyam Sharma
6     James Authur
7       Josh Wills
8         Leo Duck
Name: name, dtype: object

In [8]:
df[df.department.isin(["Sales","Operations"])]

name   age   income gender  department grade  performance_score
0    Allen Smith  45.0      NaN    NaN  Operations    G3                723
3      Ying Chin  45.0  65000.0      F       Sales    G3                556
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2                711
5  Satyam Sharma   NaN  62000.0    NaN       Sales    G3                649
6   James Authur  54.0      NaN      F  Operations    G3                 53
8       Leo Duck  23.0  98000.0      M       Sales    G4                709

In [9]:
df[df.performance_score >=500]

name   age   income gender  department grade  performance_score
0    Allen Smith  45.0      NaN    NaN  Operations    G3                723
1        S Kumar   NaN  16000.0      F     Finance    G0                520
2    Jack Morgan  32.0  35000.0      M     Finance    G2                674
3      Ying Chin  45.0  65000.0      F       Sales    G3                556
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2                711
5  Satyam Sharma   NaN  62000.0    NaN       Sales    G3                649
7     Josh Wills  54.0  52000.0      F     Finance    G3                901
8       Leo Duck  23.0  98000.0      M       Sales    G4                709

In [10]:
df[(df.performance_score >=500) & (df.performance_score < 700)]

name   age   income gender department grade  performance_score
1        S Kumar   NaN  16000.0      F    Finance    G0                520
2    Jack Morgan  32.0  35000.0      M    Finance    G2                674
3      Ying Chin  45.0  65000.0      F      Sales    G3                556
5  Satyam Sharma   NaN  62000.0    NaN      Sales    G3                649

In [12]:
df.query("performance_score <500")

name   age  income gender  department grade  performance_score
6  James Authur  54.0     NaN      F  Operations    G3                 53

In [13]:
df2 = df.dropna()
df2

name   age   income gender  department grade  performance_score
2    Jack Morgan  32.0  35000.0      M     Finance    G2                674
3      Ying Chin  45.0  65000.0      F       Sales    G3                556
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2                711
7     Josh Wills  54.0  52000.0      F     Finance    G3                901
8       Leo Duck  23.0  98000.0      M       Sales    G4                709

In [14]:
df2["age"]=df2.age.fillna(df2.age.mean())
df2

df2["income"]=df2.income.fillna(df2.income.median())
df2

df2["gender"]=df2.gender.fillna(df2.gender.mode()[0])
df2

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_1496\3459542096.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["age"]=df2.age.fillna(df2.age.mean())
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_1496\3459542096.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["income"]=df2.income.fillna(df2.income.median())
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_1496\3459542096.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_i

name   age   income gender  department grade  performance_score
2    Jack Morgan  32.0  35000.0      M     Finance    G2                674
3      Ying Chin  45.0  65000.0      F       Sales    G3                556
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2                711
7     Josh Wills  54.0  52000.0      F     Finance    G3                901
8       Leo Duck  23.0  98000.0      M       Sales    G4                709

In [15]:
df3 = df
upper_limit = df3['performance_score'].quantile(.99)
lower_limit = df3['performance_score'].quantile(.01)
df3 = df3[(df3['performance_score'] < upper_limit) &
(df3['performance_score'] > lower_limit)]
df3

name   age   income gender  department grade  performance_score
0    Allen Smith  45.0      NaN    NaN  Operations    G3                723
1        S Kumar   NaN  16000.0      F     Finance    G0                520
2    Jack Morgan  32.0  35000.0      M     Finance    G2                674
3      Ying Chin  45.0  65000.0      F       Sales    G3                556
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2                711
5  Satyam Sharma   NaN  62000.0    NaN       Sales    G3                649
8       Leo Duck  23.0  98000.0      M       Sales    G4                709

In [16]:

encoded_data = pd.get_dummies(df["gender"])
df = df.join(encoded_data)
df.head()

name   age   income gender  department grade  performance_score  \
0    Allen Smith  45.0      NaN    NaN  Operations    G3                723   
1        S Kumar   NaN  16000.0      F     Finance    G0                520   
2    Jack Morgan  32.0  35000.0      M     Finance    G2                674   
3      Ying Chin  45.0  65000.0      F       Sales    G3                556   
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2                711   

       F      M  
0  False  False  
1   True  False  
2  False   True  
3   True  False  
4   True  False

In [17]:
onehotencoder = OneHotEncoder()
df['gender']=df['gender'].fillna(df['gender'].mode()[0])
onehotencoder.fit_transform(df[['gender']]).toarray()


array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.]])

In [18]:
label_encorder = LabelEncoder()
encoded_data1 = label_encorder.fit_transform(df["department"])
print(encoded_data1)

[1 0 0 2 1 2 1 0 2]


In [19]:
label_encorder = LabelEncoder()
encoded_data1 = label_encorder.fit_transform(df["department"])
print(encoded_data1)

[1 0 0 2 1 2 1 0 2]


In [20]:
inverse_encode=label_encorder.inverse_transform([0, 0, 1, 2])
print(inverse_encode)

order_encoder=OrdinalEncoder(categories=['G0','G1','G2','G3','G4'])
df['grade_encoded'] = label_encorder.fit_transform(df['grade'])
df.head()

['Finance' 'Finance' 'Operations' 'Sales']


name   age   income gender  department grade  performance_score  \
0    Allen Smith  45.0      NaN      F  Operations    G3                723   
1        S Kumar   NaN  16000.0      F     Finance    G0                520   
2    Jack Morgan  32.0  35000.0      M     Finance    G2                674   
3      Ying Chin  45.0  65000.0      F       Sales    G3                556   
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2                711   

       F      M  grade_encoded  
0  False  False              2  
1   True  False              0  
2  False   True              1  
3   True  False              2  
4   True  False              1

In [21]:
scaler = StandardScaler()
scaler.fit(df['performance_score'].values.reshape(-1,1))
df['performance_std_scaler']=scaler.transform(df['performance_score'].values.reshape(-1,1))
df.head()

name   age   income gender  department grade  performance_score  \
0    Allen Smith  45.0      NaN      F  Operations    G3                723   
1        S Kumar   NaN  16000.0      F     Finance    G0                520   
2    Jack Morgan  32.0  35000.0      M     Finance    G2                674   
3      Ying Chin  45.0  65000.0      F       Sales    G3                556   
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2                711   

       F      M  grade_encoded  performance_std_scaler  
0  False  False              2                0.505565  
1   True  False              0               -0.408053  
2  False   True              1                0.285037  
3   True  False              2               -0.246032  
4   True  False              1                0.451558

In [22]:
scaler = MinMaxScaler()
scaler.fit(df['performance_score'].values.reshape(-1,1))
df['performance_minmax_scaler']=scaler.transform(df['performance_score'].values.reshape(-1,1))
df.head()


name   age   income gender  department grade  performance_score  \
0    Allen Smith  45.0      NaN      F  Operations    G3                723   
1        S Kumar   NaN  16000.0      F     Finance    G0                520   
2    Jack Morgan  32.0  35000.0      M     Finance    G2                674   
3      Ying Chin  45.0  65000.0      F       Sales    G3                556   
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2                711   

       F      M  grade_encoded  performance_std_scaler  \
0  False  False              2                0.505565   
1   True  False              0               -0.408053   
2  False   True              1                0.285037   
3   True  False              2               -0.246032   
4   True  False              1                0.451558   

   performance_minmax_scaler  
0                   0.790094  
1                   0.550708  
2                   0.732311  
3                   0.593160  
4                   0.775943